http:
  build: ./http/
  ports:
   - "80:80"
   - "443:443"
jira:
  build: ./jira/
  links:
   - db
  ports:
   - "8080:8080"
  volumes:
   - /data/atlassian:/var/atlassian
db:
  build: ./db/
  environment:
    POSTGRES_USER: atlassian
    POSTGRES_PASSWORD: atlassian
  expose:
    - "5432"
  volumes:
    - /data/postgres:/var/lib/postgresql/data
