http:
  build: ./http/
  ports:
   - "80:80"
   - "443:443"
  links:
   - jira
   - stash
   - bamboo

jira:
  build: ./jira/
  links:
   - db
  ports:
   - "8080:8080"
  volumes:
   - /data/atlassian:/var/atlassian

stash:
  build: ./stash/
  links:
   - db
  ports:
   - "7999:7999"
   - "7990:7990"
  volumes:
   - /data/atlassian:/var/atlassian

bamboo:
  build: ./bamboo/
  links:
   - db
  ports:
   - "8085:8085"
  volumes:
   - /data/atlassian:/var/atlassian

db:
  build: ./db/
  environment:
    POSTGRES_USER: atlassian
    POSTGRES_PASSWORD: atlassian
  expose:
    - "5432"
  volumes:
    - /data/postgres:/var/lib/postgresql/data
